### ISSUE TITLE
Honeygain logout after work

### ISSUE THREAD

**Issue by toshmop** [ziggyds/honeygain-honeypot#1]
Hello, two things.
1- The Honeygain instance goes offline when honeygain-daily has finished working
2- how to change the time? because waiting 10 p.m. for the tests is not practical
Thanks

**Comment by zidesm** [comment]
You can change the time by building your own container using the provided dockerfile or you can mount the crontab file and change the time in there.

As for your first issue. Without further details I can't really help. The container should just keep running if you provided the mandatory env vars the script expects.

**Comment by toshmop** [comment]
thank you for your answer, i will try it
