### ISSUE TITLE
How to get JWT_TOKEN and DISCORD_WEBHOOK

### ISSUE THREAD

**Issue by alexsorel** [ziggyds/honeygain-honeypot#3]
Hi, thanks a lot for your job, works like a charm. But I would like to set up a second docker container for another Honeygain account, and I forgot how to retrieve the JWT_TOKEN and DISCORD_WEBHOOK tokens. Can you remind me where to go?

**Comment by zidesm** [comment]
The easiest manual method is still:

1. Log on to the honeygain dashboard (website)
2. Right click and inspect or hit F12
3. Application tab
4. Local storage section and click the dashboard.honeygain.com url
5. Et voila, you should see a JWT key value pair

Regarding the discord hook. If you are not using it, put a random string
